apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-demo-deployment
spec:
  replicas: 2  # 두 개의 복제본을 생성
  selector:
    matchLabels:
      app: springboot-demo
  template:
    metadata:
      labels:
        app: springboot-demo
    spec:
      containers:
        - name: springboot-demo
          image: jjeongjjeong/springboot-demo:latest  # Docker 이미지 사용
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "250m"  # 최소 250m (0.25 vCPU) 요청
              memory: "512Mi"
            limits:
              cpu: "500m"  # 최대 500m (0.5 vCPU) 사용 가능
              memory: "1024Mi"
